definitions:
  model.Recipe:
    properties:
      id:
        type: string
      ingredients:
        items:
          type: string
        type: array
      instructions:
        items:
          type: string
        type: array
      name:
        type: string
      publishedAt:
        type: string
      tags:
        items:
          type: string
        type: array
    type: object
  model.RecipeForm:
    properties:
      ingredients:
        items:
          type: string
        type: array
      instructions:
        items:
          type: string
        type: array
      name:
        type: string
      tags:
        items:
          type: string
        type: array
    type: object
info:
  contact: {}
paths:
  /recipes:
    get:
      description: List recipes.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Recipe'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: List all Recipes
    post:
      description: Create a new recipe by providing Recipe JSON data and store it
        in the database. Returns the saved recipe as JSON.
      parameters:
      - description: Recipe JSON
        in: body
        name: Recipe
        required: true
        schema:
          $ref: '#/definitions/model.RecipeForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Recipe'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create a New Recipe
    put:
      description: Update an existing recipe by providing updated Recipe JSON data.
        Returns updated recipe upon successful update.
      parameters:
      - description: Updated Recipe JSON
        in: body
        name: Recipe
        required: true
        schema:
          $ref: '#/definitions/model.Recipe'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update Recipe
  /recipes/{id}:
    delete:
      description: Delete a recipe by providing its unique identifier (ID). Returns
        a confirmation message upon successful deletion.
      parameters:
      - description: Recipe ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete Recipe
  /recipes/search:
    get:
      description: Search for recipes based on specified tags. Returns a list of matching
        recipes.
      parameters:
      - description: Comma-separated list of tags for filtering
        in: query
        name: tags
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Recipe'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Search Recipes
swagger: "2.0"
